let pokemonList = [
  {name: 'bulbuasaur', height: .7, type: ['grass', 'poison']},
  {name: 'ivysaur', height: 1, type: ['grass', 'poison']},
  {name: 'veusaur', height: 2, type: ['grass', 'poison']},
  {name: 'charmander', height: .6, type: 'fire'},
  {name: 'charmeleon', height: 1.1, type: 'fire'},
  {name: 'charizard', height: 1.7, type: ['fire', 'flying']},
  {name: 'squirtle', height: .5, type: 'water'},
  {name: 'wartortle', height: 1, type: 'water'},
  {name: 'blastoise', height: 1.6, type: 'water'},
  {name: 'caterpie', height: .3, type: 'bug'},
  {name: 'metapod', height: .7, type: 'bug'},
  {name: 'butterfree', height: 1.1, type: ['bug', 'flying']},
  {name: 'weedle', height: .3, type: ['bug', 'poison']},
  {name: 'kakuna', height: .6, type: ['bug', 'poison']},
  {name: 'beedrill', height: 1, type: ['bug', 'poison']},
  {name: 'pidgey', height: .3, type: ['flying', 'normal']},
  {name: 'pidgeotto', height: 1.1, type: ['flying', 'normal']},
  {name: 'pidgeot', height: 1.5, type: ['flying', 'normal']},
  {name: 'rattata', height: .3, type: 'normal'},
  {name: 'raticate', height: .7, type: 'normal'},
  {name: 'spearow', height: .3, type: ['flying', 'normal']},
  {name: 'fearow', height: 1.2, type: ['flying', 'normal']},
  {name: 'ekans', height: 2, type: 'poison'},
  {name: 'arbok', height: 3.5, type: 'poison'},
  {name: 'pikachu', height: .4, type: 'electric'},
  {name: 'raichu', height: .8, type: 'electric'}
]
